#!/usr/bin/env python3
import os
import sys
import time

sys.stdin.read()
mode = os.environ.get("FAKE_CODEX_MODE", "nonjson")
if mode == "timeout":
    time.sleep(6)
elif mode == "nonzero":
    sys.exit(7)
else:
    sys.stdout.write(os.environ.get("FAKE_CODEX_RESPONSE", "not json"))
